jobs:
  runs:
    db:
      use: create-db
      with:
        pgAdminSecretRefName: pg-scaleway
        # pgSecretName: "hasura-db-{{ .Values.global.branchSlug32 }}"
        # database: "hasura_{{ .Values.global.branchSlug32 }}"
        # pgUser: "hasura_{{ .Values.global.branchSlug32 }}"

deactivate:
  enabled: false
  jobs-deactivate:
    runs:
      deactivate:
        with:
          pgAdminSecretRefName: pg-scaleway
      # drop-db2:
      #   use: drop-db
      #   with:
      #     pgAdminSecretRefName: pg-scaleway
      #     database: "hasura_{{ .Values.global.branchSlug32 }}"
