#!/usr/bin/env bash
set -e
echo "
REPOSITORY=${REPOSITORY:-$GITHUB_REPOSITORY}
GIT_HEAD_REF=${GIT_HEAD_REF:-$GITHUB_HEAD_REF}
GIT_REF=${GIT_REF:-$GITHUB_REF}
WORKSPACE_PATH=${WORKSPACE_PATH:-$GITHUB_WORKSPACE}
KUBEWORKFLOW_PATH=${KUBEWORKFLOW_PATH:-$GITHUB_ACTION_PATH}
"