build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/busybox/sh","-c"]
  script:
    - |
      mkdir -p /kaniko/.docker
      echo "{\"auths\":{\"$HARBOR\":{\"username\":\"$HARBOR_USER\",\"password\":\"$HARBOR_PASSWORD\"}}}" > /kaniko/.docker/config.json
        /kaniko/executor \
        --context="dir://${CI_PROJECT_DIR}" \
        --dockerfile="${CI_PROJECT_DIR}/Dockerfile" \
        --destination="${HARBOR}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}" \
        --cache=true
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'