nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - checksum: be1dba27c561e35587f6130f0c9685e83768e34e7aafa3587e2f3782baab594bb3634516348bfcb44406e529676f9166f573d2d6cc732bb4e8077b3e7b92f870
    path: .yarn/plugins/@yarnpkg/plugin-fetch.cjs
    spec: "https://raw.githubusercontent.com/devthejo/yarn-plugin-fetch/master/bundles/@yarnpkg/plugin-fetch.js"

yarnPath: .yarn/releases/yarn-4.0.0-rc.39.cjs
