name: "Autodevops deploy"
description: "Autodevops deploy using Helm template and kapp"
inputs:
  environment:
    description: "The deployment environment (dev | preprod | prod)"
    required: true
  rancherProjectId:
    description: "The Rancher project ID, usually secrets.RANCHER_PROJECT_ID"
    required: true
  rancherProjectName:
    description: "The Rancher project name, usually secrets.RANCHER_PROJECT_NAME, usefull jobs that needs secrets or ci namespaces"
    required: true
  kubeconfig:
    description: "The Kubernetes authentication configuration"
  token:
    description: "The Github authentication token"
  charts:
    description: "comma separated list of charts to enable as standalone"
  subcharts:
    description: "comma separated list of subcharts to enable as a part of the main chart"
  actionName:
    description: "override manifests name as manifest-$name.yaml, default to manifest-$environment.yaml"
  timeout:
    description: "override default kapp --wait-timeout, default to 15m0s"
outputs:
  url:
    description: "Main deployment URL"
    value: ${{ steps.environment-url.outputs.url }}
runs:
  using: "composite"
  steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup env
      shell: bash
      run: |
        KWBUILD_PATH=/tmp/autodevops
        mkdir -p $KWBUILD_PATH
        echo "KWBUILD_PATH=$KWBUILD_PATH" >> $GITHUB_ENV

    - name: Install dependencies
      shell: bash
      working-directory: "${{ github.action_path }}"
      run: |
        # yarn --immutable
        yarn workspaces focus kube-workflow --production

    - name: Build manifests
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        RANCHER_PROJECT_ID: ${{ inputs.rancherProjectId }}
        RANCHER_PROJECT_NAME: ${{ inputs.rancherProjectName }}
        KW_CHARTS: ${{ inputs.charts }}
        KW_SUBCHARTS: ${{ inputs.subcharts }}
        DEBUG: "true"
      working-directory: "${{ github.action_path }}"
      run: packages/workflow/bin/kube-workflow build --cwd ${{ github.workspace }}

    - name: Archive manifest
      uses: actions/upload-artifact@v2
      with:
        name: manifests-${{ inputs.actionName || inputs.environment }}.yaml
        path: ${{ env.KWBUILD_PATH }}/manifests.yaml

    - name: Setup namespace env var
      shell: bash
      working-directory: ${{ env.KWBUILD_PATH }}
      run: |
        NAMESPACE=$(cat manifests.yaml | yq eval-all 'select(.kind=="Namespace").metadata.name')
        echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV

    - name: Notify deployment start
      uses: bobheadxi/deployments@v0.4.3
      id: deployment
      with:
        step: start
        token: ${{ inputs.token }}
        desc: "Deploying environment: ${{ env.NAMESPACE }}"
        env: ${{ inputs.environment == 'dev' && env.NAMESPACE || inputs.environment == 'preproduction' && 'preproduction' || 'production' }}
        
    - name: Install Kapp
      uses: vmware-tanzu/carvel-setup-action@v1
      with:
        only: kapp
        token: ${{ inputs.token }}

    - name: Create kubernetes config
      shell: bash
      run: |
        mkdir -p ~/.kube
        touch ~/.kube/config
        echo ${{ inputs.kubeconfig }} | base64 -d > ~/.kube/config
    
    - name: Deploy manifests
      shell: bash
      working-directory: "${{ github.action_path }}"
      env:
        GIT_REPOSITORY: ${{ github.repository }}
        ENVIRONMENT: ${{ inputs.environment }}
        RANCHER_PROJECT_ID: ${{ inputs.rancherProjectId }}
        RANCHER_PROJECT_NAME: ${{ inputs.rancherProjectName }}
        KW_DEPLOY_TIMEOUT: ${{ inputs.timeout }}
      run: packages/workflow/bin/kube-workflow deploy --cwd ${{ github.workspace }} -f ${{ env.KWBUILD_PATH }}/manifests.yaml

    - name: Define environment URL
      id: environment-url
      shell: bash
      working-directory: ${{ env.KWBUILD_PATH }}
      run: |
        HOSTS=$(cat manifests.yaml | yq eval-all '.spec.rules[] .host')
        HOST=$(echo "$HOSTS" | head -n 1)
        echo $HOST
        echo "::set-output name=url::https://$HOST"

    - name: Notify deployment end
      uses: bobheadxi/deployments@v0.4.3
      with:
        step: finish
        status: ${{ job.status }}
        token: ${{ inputs.token }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        env_url: ${{ steps.environment-url.outputs.url }}

    - name: Debug manifests
      uses: SocialGouv/actions/k8s-manifests-debug@v1
      with:
        token: ${{ inputs.token }}
        path: ${{ env.KWBUILD_PATH }}/manifests.yaml
