version: "3.8"

services:
  webhook:
    image: kubeworkflow_webhook
    restart: always
    build:
      context: .
      dockerfile: ./packages/webhook/Dockerfile.dev
    volumes:
      - ./.dev-secrets:/secrets:ro
      - ./:/app
    ports:
      - ${KUBEWORKFLOW_WEBHOOK_EXPOSE_PORT:-7530}:3000
    environment:
      LOG_REQUESTS: ${LOG_REQUESTS:-false}
