version: "3.8"

services:
  webhook:
    image: kubeworkflow_webhook
    restart: always
    build:
      context: .
      dockerfile: ./packages/webhook/Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - ${KUBEWEBHOOK_EXPOSED_PORT:-7530}:3000
    environment:
      LOG_REQUESTS: ${LOG_REQUESTS:-false}
      KUBEWEBHOOK_TOKEN: ${KUBEWEBHOOK_TOKEN:-1234}
      KUBEWEBHOOK_EXPOSED_PORT: ${KUBEWEBHOOK_EXPOSED_PORT:-7530}
