version: "3.8"

services:
  webhook:
    image: kubeworkflow_webhook
    restart: always
    build:
      context: .
      dockerfile: ./packages/webhook/Dockerfile.dev
    volumes:
      - ./:/app
      - ${KUBECONFIG:-$HOME/.kube/config}:/home/ubuntu/.kube/config:ro
    ports:
      - ${KUBEWEBHOOK_EXPOSED_PORT:-7530}:3000
    environment:
      KS_RANCHER_PROJECT_NAME: ${KS_RANCHER_PROJECT_NAME:-sample-next-app}
      KUBEWEBHOOK_TOKEN: ${KUBEWEBHOOK_TOKEN:-1234}
      KUBEWEBHOOK_EXPOSED_PORT: ${KUBEWEBHOOK_EXPOSED_PORT:-7530}
