version: "3.8"

services:
  webhook:
    image: kontinuous_webhook_prod
    restart: always
    build:
      context: .
      dockerfile: ./packages/webhook/Dockerfile
    volumes:
      - ${KUBECONFIG:-$HOME/.kube/config}:/home/ubuntu/.kube/config:ro
    ports:
      - ${KUBEWEBHOOK_EXPOSED_PORT:-7530}:3000
    environment:
      RANCHER_PROJECT_NAME: ${RANCHER_PROJECT_NAME:-sample-next-app}
      KUBEWEBHOOK_SUPERTOKEN: ${KUBEWEBHOOK_SUPERTOKEN:-1234}
      KUBEWEBHOOK_EXPOSED_PORT: ${KUBEWEBHOOK_EXPOSED_PORT:-7530}
      KUBEWEBHOOK_SENTRY_DSN: ${KUBEWEBHOOK_SENTRY_DSN}

