version: "3.8"

services:
  webhook:
    image: kontinuous_webhook
    restart: always
    build:
      context: .
      dockerfile: ./packages/webhook/Dockerfile.dev
    volumes:
      - ./:/app
      - ${KUBECONFIG:-~/.kube/config}:/home/ubuntu/.kube/config:ro
    ports:
      - ${KUBEWEBHOOK_EXPOSED_PORT:-7530}:3000
    environment:
      KUBEWEBHOOK_CONFIG_PATH: config.sample.yaml
      KUBEWEBHOOK_SUPERTOKEN: ${KUBEWEBHOOK_SUPERTOKEN:-1234}
      KUBEWEBHOOK_EXPOSED_PORT: ${KUBEWEBHOOK_EXPOSED_PORT:-7530}
      KUBEWEBHOOK_PIPELINE_IMAGE: ${KUBEWEBHOOK_PIPELINE_IMAGE:-"ghcr.io/socialgouv/kontinuous:v1.97.8"}
      KUBEWEBHOOK_PIPELINE_CHECKOUT_IMAGE: ${KUBEWEBHOOK_PIPELINE_CHECKOUT_IMAGE:-"ghcr.io/socialgouv/kontinuous/degit:v1.97.8"}
      KS_LOG_LEVEL: "trace"
