version: "3.8"

services:
  webhook:
    image: kontinuous_webhook
    restart: always
    build:
      context: .
      dockerfile: ./packages/webhook/Dockerfile.dev
    volumes:
      - ./:/app
      - ${KUBECONFIG:-$HOME/.kube/config}:/home/ubuntu/.kube/config:ro
    ports:
      - ${KUBEWEBHOOK_EXPOSED_PORT:-7530}:3000
    environment:
      KUBEWEBHOOK_SUPERTOKEN: ${KUBEWEBHOOK_SUPERTOKEN:-1234}
      KUBEWEBHOOK_EXPOSED_PORT: ${KUBEWEBHOOK_EXPOSED_PORT:-7530}
      RANCHER_PROJECT_NAME: ${RANCHER_PROJECT_NAME:-sample-next-app}
      KS_CI_NAMESPACE: ${KS_CI_NAMESPACE:-sample-next-app-ci}
