apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jobci-clean-workflow
  namespace: {{ or .Values.namespace .Values.global.jobNamespace }}
  annotations: {}
spec:
  schedule: "0 0 * * *" # Run once a day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: job
              image: bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              envFrom:
              - secretRef:
                  name: kubeconfig
              command:
                - /bin/bash
                - -c
                - |
                  echo "$KUBECONFIG" > ~/.kube/config
                  export KUBECONFIG=~/.kube/config
                  JOBS=$(kubectl get jobs -n sample-next-app-ci -o json | jq ".items | .[] .status | select(.active > 0)")
                  for dir in /workflow/*; do
                    [ -d "$dir" ] || continue
                    if [ -z $(echo $JOBS | grep -e "${dir##*/}") ]; then
                      rm -rf $dir
                    fi
                  done
              volumeMounts:
                - name: workflow
                  mountPath: /workflow

          volumes:
            - name: workflow
              persistentVolumeClaim:
                claimName: jobs-shared-storage