enabled:
namespace: 
host: 
image: 
imagePackage: app
imageTag: 
ttl: 
rancherProjectId: my-cluser-id:my-project-id
isProduction: false
isPreProduction: false
replicas: 1
containerPort: 3000
servicePort: 80
env: []
envFrom: []
probesPath: /index.html
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
autoscale:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  averageUtilization:
    cpu: 100
    memory: 100
certSecretName: 
waitForPostgres: false
addVolumes: []
volumes: []
volumeMounts: []
redirectFrom: []