name: Review
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  deploy:
    uses: socialgouv/kontinuousv1.95.6
    secrets: inherit
    with:
      triggerWebhook: true # comment this line when enabling webhook on repository
