name: Deactivate
on:
  delete:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  cleaning:
    uses: socialgouv/kontinuousv1.95.6
    secrets: inherit
