name: Go to Production
on:
  push:
    tags:
      - v*

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  production:
    uses: SocialGouv/kontinuous/.github/workflows/workflow-gotoprod-manual.yaml@v1
    secrets: inherit
