name: Production
on:
  push:
    tags:
      - v*

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  deploy:
    uses: socialgouv/kontinuousv1.95.6
    secrets: inherit
