kontinuous-webhook:
  image: ghcr.io/socialgouv/kontinuous/webhook:v1.176.9
  # image: harbor.fabrique.social.gouv.fr/sre/kontinuous/webhook:1
  host: "kontinuous.fabrique.social.gouv.fr"
  
  # conventioned kube native permissions binding
  ciNamespace:
    allowAll: true
    template: "${project}-ci"

  # specific access permissions binding
  # kubeconfigSecrets:
  #   - name: kubeconfig-dev-fabrique
  #     cluster: dev
  #     project: fabrique
  #   - name: kubeconfig-prod-fabrique
  #     cluster: prod
  #     project: fabrique

  # specific token secret
  # tokenSecrets:
  #   - name: webhook-token-fabrique
  #     project: fabrique
    
  # reloadable tokens secret
  reloadableTokensSecret:
    enabled: true
    name: "reloadable-tokens-secret"