name: "Reporting of Kontinuous Webhook Pipeline for Github"
inputs:
  token:
    description: "The Github authentication token"
    required: true
  deployment_id:
    description: "Deployment id"
    required: true
outputs:
  url:
    description: "Main deployment URL"
    value: ${{ steps.environment-url.outputs.url }}
runs:
  using: "composite"
  steps:
    - name: Archive manifest
      uses: actions/upload-artifact@v3
      with:
        name: manifests.yaml
        path: manifests.yaml
    
    - name: Notify deployment end
      uses: bobheadxi/deployments@v1
      if: github.event_name != 'delete' && env.DEPLOYMENT_OK == 'true'
      with:
        step: finish
        status: ${{ job.status }}
        token: ${{ inputs.token }}
        env_url: ${{ env.DEPLOYMENT_URL }}
        env: ${{ env.DEPLOYMENT_NAME }}
        deployment_id: ${{ inputs.deployment_id }}
    
    - name: Clean deployment
      uses: bobheadxi/deployments@v1
      if: github.event_name == 'delete'
      with:
        step: deactivate-env
        token: ${{ inputs.token }}
        env: ${{ env.DEPLOYMENT_NAME }}
        desc: Environment was pruned

    - name: Debug manifests
      uses: socialgouv/kontinuous/.github/actions/debug-manifests@v1.109.5
      if: github.event_name != 'delete'
      with:
        token: ${{ inputs.token }}

    - name: Report pipeline status
      shell: bash
      run: |
        if [ "$DEPLOYMENT_OK" != "true" ]; then
          echo "Pipeline failed ❌"
          echo 'see "Kontinuous Pipeline 🥷" step to inspect full logs'
          exit 1
        fi