name: "Kontinuous Pipeline 🥷"
description: "Deploy on Kubernetes via Webhook"
inputs:
  webhookToken:
    description: "The webhook authentication token, usually secrets.KUBEWEBHOOK_TOKEN"
  webhookUri:
    description: "The webhook uri"
  triggerWebhook:
    description: "Trigger webhook on first call, useful when webhooks are not configured on the repo"
  environment:
    description: "The deployment environment (dev | preprod | prod), default to prod on version tag, preprod on master or main, else dev"
  chart:
    description: "charts to enable as standalone, you can add multiple separated by comma"
  ignoreProjectTemplates:
    description: "don't merge project's root templates and env templates"
  deployWriteOutputFile:
    description: "Set file to tee output of kontinuous logs command"
    default: ""
  projectName:
    description: "projectName for kontinuous, usually the rancher project name"
    default: ""

runs:
  using: docker
  # image: Dockerfile
  image: docker://ghcr.io/socialgouv/kontinuous/deploy-via-webhook:v1.147.5
  env:
    KS_WEBHOOK_TOKEN: ${{ inputs.webhookToken }}
    KS_WEBHOOK_URI: ${{ inputs.webhookUri }}
    TRIGGER_WEBHOOK: ${{ inputs.triggerWebhook }}
    KS_ENVIRONMENT: ${{ inputs.environment }}
    KS_CHART: ${{ inputs.chart }}
    KS_IGNORE_PROJECT_TEMPLATES: ${{ inputs.ignoreProjectTemplates }}
    KS_DEPLOY_WRITE_OUTPUT_FILE: ${{ inputs.deployWriteOutputFile }}
    KS_PROJECT_NAME: ${{ inputs.projectName }}