name: "Reporting of Kontinuous Webhook Pipeline for Github"
inputs:
  token:
    description: "The Github authentication token"
outputs:
  url:
    description: "Main deployment URL"
    value: ${{ steps.environment-url.outputs.url }}
runs:
  using: "composite"
  steps:
    - name: Archive manifest
      uses: actions/upload-artifact@v3
      with:
        name: manifests.yaml
        path: manifests.yaml

    - name: Check deployment status
      shell: bash
      run: |
        if [ "$DEPLOYMENT_OK" != "true" ]; then
          exit 1
        fi

    - name: Notify deployment end
      uses: bobheadxi/deployments@v1
      with:
        step: finish
        status: ${{ job.status }}
        token: ${{ inputs.token }}
        env_url: ${{ env.DEPLOYMENT_URL }}
        deployment_id: ${{ env.DEPLOYMENT_ID }}

    - name: Debug manifests
      uses: SocialGouv/kontinuous/gh-actions/debug-manifests@v1
      with:
        token: ${{ inputs.token }}
        path: manifests.yaml
