name: "Debug manifests generate output"
description: "Run a kontinuous pipeline on kubernetes via webhook"
inputs:
  path:
    description: "Your manifests YAML file path"
runs:
  using: docker
  # image: Dockerfile
  image: docker://ghcr.io/socialgouv/kontinuous/gh-action-debug-manifests-output:v1.109.18
  args:  
    - '${{ inputs.path }}'
