name: "Starting deployment"
inputs:
  token:
    description: "The Github authentication token"
    required: true
outputs:
  deployment_id:
    description: "Deployment id"
    value: ${{ steps.deployment.outputs.deployment_id }}
runs:
  using: "composite"
  steps:
    - name: Load kontinuous config
      id: kontinuous-config
      uses: socialgouv/kontinuous/.github/actions/load-remote-config@v1.96.6
    
    - name: Notify deployment start
      uses: bobheadxi/deployments@v1
      id: deployment
      with:
        step: start
        token: ${{ inputs.token }}
        override: true
        desc: "Deploying environment: ${{ steps.kontinuous-config.outputs.deployment_name }}"
        env: ${{ steps.kontinuous-config.outputs.deployment_name }}
