name: "Kontinuous Pipeline 🥷"
description: "Deploy on Kubernetes via Github"
inputs:
  environment:
    description: "The deployment environment (dev | preprod | prod), default to prod on version tag, preprod on master or main, else dev"
  chart:
    description: "charts to enable as standalone, you can add multiple separated by comma"
  ignoreProjectTemplates:
    description: "don't merge project's root templates and env templates"
  cwd:
    description: "working directory where is located .kontinuous"
  kubeconfig:
    description: "The Kubernetes authentication configuration content"
  kubeconfigContext:
    description: "override kubeconfig context, default dev or prod according to environment"
  inlineValues:
    description: "deep final override of values in yaml format"
  inlineSet:
    description: "override final values using in yaml format, supporting subkeys"
  logLevel:
    description: "Set kontinuous logger verbosity, possible values: trace, debug, info, warn, error"
    default: "debug"
  deployWriteOutputFile:
    description: "Set file to tee output of kontinuous deploy command"
    default: ""
  sentryDSN:
    description: "Sentry DSN for error reporting"
    default: ""
  notifyWebhookUrl:
    description: "Notify webhook url secret targeting mattermost or slack channel"
    default: ""
  ciNamespace:
    description: "CI namespace name for kontinuous"
    default: ""
  projectName:
    description: "projectName for kontinuous, usually the rancher project name"
    default: ""
  inlineConfig:
    description: "Set config values using yaml format"
    default: ""
  configSet:
    description: "Set config values using dot notation. eg: my.config.key=value,another.config.key=value2"
    default: ""

runs:
  using: docker
  # image: Dockerfile
  image: docker://ghcr.io/socialgouv/kontinuous/deploy-via-github:v1.164.6
  env:
    KS_ENVIRONMENT: ${{ inputs.environment }}
    KS_CHART: ${{ inputs.chart }}
    KS_IGNORE_PROJECT_TEMPLATES: ${{ inputs.ignoreProjectTemplates }}
    KS_WORKSPACE_PATH: ${{ inputs.cwd }}
    KUBECONFIG_B64: ${{ inputs.kubeconfig }}    
    KS_KUBECONFIG_CONTEXT: ${{ inputs.kubeconfigContext }}    
    KS_INLINE_VALUES: ${{ inputs.inlineValues }}    
    KS_INLINE_SET: ${{ inputs.inlineSet }}    
    KS_LOG_LEVEL: ${{ inputs.logLevel }}
    KS_DEPLOY_WRITE_OUTPUT_FILE: ${{ inputs.deployWriteOutputFile }}
    KS_NOTIFY_WEBHOOK_URL: ${{ inputs.notifyWebhookUrl }}
    KS_SENTRY_DSN: ${{ inputs.sentryDSN }}
    KS_CI_NAMESPACE: ${{ inputs.ciNamespace }}
    KS_PROJECT_NAME: ${{ inputs.projectName }}
    KS_INLINE_CONFIG: ${{ inputs.inlineConfig }}
    KS_INLINE_CONFIG_SET: ${{ inputs.configSet }}