{{ if gt (len .Values.redirectFrom) 0 }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ or .Values.component .Chart.Name }}-redirect"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: https://{{ or .Values.host .Values.global.host }}$request_uri
    {{ range $key, $val := (merge .Values.global.ingress.annotations .Values.ingress.annotations) }}
    "{{ $key }}": "{{ $val }}"
    {{ end }}
spec:
  rules:
  {{ range $host := .Values.redirectFrom }}
    - host: "{{ tpl $host $ }}"
  {{ end }}
  tls:
    - hosts:
      {{ range $host := .Values.redirectFrom }}
        - "{{ tpl $host $ }}"
      {{ end }}
      secretName: "{{ or .Values.component .Chart.Name }}-redirect"
{{ end }}