apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ or .Values.component .Chart.Name }}
    application: {{ .Values.global.repositoryName }}
  name: {{ or .Values.component .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: 8081
  selector:
    component: {{ or .Values.component .Chart.Name }}
  type: ClusterIP
  