{{ if .Values.extra.enableJobs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobs-shared-storage
  annotations: {}
  labels: {}
  namespace: {{ or .Values.namespace .Values.global.jobNamespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.sharedStorage.size }}
  storageClassName: {{ .Values.sharedStorage.className }}
{{ end }}