apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: {{ or .Values.component .Chart.Name }}
  name: {{ or .Values.component .Chart.Name }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- else }}
  namespace: webhook-{{ .Values.rancherProjectName }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      component: {{ or .Values.component .Chart.Name }}
  template:
    metadata:
      labels:
        component: {{ or .Values.component .Chart.Name }}
    spec:
      containers:
        - name: webhook
          image: {{ .Values.image }}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 15
            httpGet:
              path: {{ .Values.probesPath }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          readinessProbe:
            failureThreshold: 15
            httpGet:
              path: {{ .Values.probesPath }}
              port: http
            initialDelaySeconds: 0
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          startupProbe:
            failureThreshold: 12
            httpGet:
              path: {{ .Values.probesPath }}
              port: http
            periodSeconds: 5
          env:
            - name: RANCHER_PROJECT_NAME
              value: "{{ required "rancherProjectName value is required" .Values.rancherProjectName }}"
            - name: KUBEWEBHOOK_EXPOSED_HOST
              value: "{{ .Values.host }}"
            - name: KUBEWEBHOOK_EXPOSED_HTTPS
              value: "true"
            - name: KUBEWEBHOOK_EXPOSED_PORT
              value: "443"
          envFrom:
            {{ range $secretRefName := .Values.secretRefNames }}
            - secretRef:
                name: "{{ $secretRefName }}"
            {{ end }}
            