apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ if .Values.isProdCluster }}
    cert-manager.io: cluster-issuer
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  labels:
    component: {{ or .Values.component .Chart.Name }}
  name: "{{ or .Values.component .Chart.Name }}"
  {{ if ne .Release.Namespace "default" }}
  namespace: "{{ .Release.Namespace }}"
  {{ end }}
spec:
  rules:
    - host: >-
        {{- tpl (required "host value is required" .Values.host) $ | nindent 8 }}
      http:
        paths:
          - backend:
              service:
                name: {{ or .Values.component .Chart.Name }}
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - >-
          {{- tpl .Values.host $ | nindent 10 }}
      {{- if .Values.isProdCluster }}
      secretName: {{ or .Values.certSecretName (print (or .Values.component .Chart.Name) "-crt") }}
      {{- else }}
      secretName: "wildcard-crt"
      {{- end }}