{{ if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    {{ if .Values.rancherProjectId }}
    field.cattle.io/projectId: "{{ .Values.rancherProjectId }}"
    {{- end }}
    {{ if not .Values.isProdCluster }}
    cert: wildcard
    {{- end }}
  {{- if .Values.namespace }}
  name: {{ .Values.namespace }}
  {{- else }}
  name: webhook-{{ .Values.rancherProjectName }}
  {{- end }}
{{ end }}