apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifacts
  annotations: {}
  labels: {}
  namespace: "{{ .Values.namespace }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.artifacts.storage.size }}
  storageClassName: {{ .Values.artifacts.storage.className }}