apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifacts
  annotations: {}
  labels: {}
  {{ if ne .Release.Namespace "default" }}
  namespace: "{{ .Release.Namespace }}"
  {{ end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.artifacts.storage.size }}
  storageClassName: {{ .Values.artifacts.storage.className }}