apiVersion: v1
kind: Service
metadata:
  name: {{ or .Values.component .Chart.Name }}
  namespace: "{{ .Values.namespace }}"
  labels:
    component: {{ or .Values.component .Chart.Name }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    component: {{ or .Values.component .Chart.Name }}
  type: ClusterIP