apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: {{ or .Values.component .Chart.Name }}
    application: {{ .Values.global.repositoryName }}
  name: {{ or .Values.component .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    kapp.k14s.io/nonce: ""
    kapp.k14s.io/create-strategy: fallback-on-update
    kapp.k14s.io/update-strategy: fallback-on-replace
    kapp.k14s.io/change-group: "autodevops/{{ .Values.global.namespace }}"
    kapp.k14s.io/change-group.{{ or .Values.component .Chart.Name }}: "autodevops/{{ or .Values.component .Chart.Name }}.{{ .Values.global.namespace }}"
    {{- range $need := .Values.needs }}
    kapp.k14s.io/change-rule.{{ $need }}: "upsert after upserting autodevops/{{ $need }}.{{ $.Values.global.namespace }}"
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ or .Values.component .Chart.Name }}
  template:
    metadata:
      labels:
        component: {{ or .Values.component .Chart.Name }}
        application: {{ .Values.global.repositoryName }}
    spec:
      containers:
        - image: maildev/maildev:latest
          name: maildev
          ports:
            - containerPort: 1080
              name: http
            - containerPort: 1025
              name: smtp
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          