app:
  ~needs: [build-app]
  host: "{{.Values.global.host}}"
  imagePackage: app
  containerPort: 3000
  probesPath: "/healthz"

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        buildArgs:
          COMMIT_SHA: "{{ $.Values.global.sha }}"
