{{ if .Values.global.extra.jobs.sharedStorage.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "jobci-post-operations-{{ or .Values.component .Chart.Name }}"
  namespace: {{ or .Values.namespace .Values.global.jobNamespace }}
  annotations:
    kapp.k14s.io/nonce: ""
    kapp.k14s.io/update-strategy: fallback-on-replace
    kapp.k14s.io/change-group: "autodevops/post-{{ .Values.global.namespace }}"
    kapp.k14s.io/change-rule: "upsert after upserting autodevops/{{ .Values.global.namespace }}"
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 3600
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      annotations: {}
      labels: {}
    spec:
      restartPolicy: Never
      containers:          
        - name: job
          image: "{{ or .Values.postJobImage .Values.image }}"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - rm -rf /workflow/*
          volumeMounts:
            - name: workflow
              mountPath: /workflow
              subPath: {{ .Values.global.branchSlug }}/{{ .Values.global.sha }}

      volumes:
        - name: workflow
          persistentVolumeClaim:
            claimName: jobs-shared-storage
{{- end }}