name: "⛑ Debug manifests ⛑"
description: "Debug some kubernetes manifests"
inputs:
  token:
    description: "Github token for PR comment"
runs:
  using: "composite"
  steps:
    - name: Debug manifests
      id: debug-manifests
      uses: socialgouv/kontinuous/.github/actions/debug-manifests-output@v1.95.37
      with:
        path: manifests.yaml

    - uses: jwalton/gh-find-current-pr@v1
      id: finder

    - name: ⛑ Comment PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ steps.finder.outputs.pr }}
        recreate: true
        message: |
          🎉 Deployment for commit ${{ github.sha }} :
          ${{ env.DEBUG_MANIFESTS_MARKDOWN }}
        GITHUB_TOKEN: ${{ inputs.token }}
