name: Deactivate
on:
  delete:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  cleaning:
    uses: socialgouv/kontinuous/.github/workflows/workflow-webhook.yaml@1.96.9
    secrets: inherit
