{{ if and .Values.global.extra.jobs.sharedStorage.enabled .Values.jobs.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "jobci-post-operations-{{ .Values.global.shortSha }}"
  namespace: {{ .Values.global.jobNamespace }}
  annotations:
    kapp.k14s.io/nonce: ""
    kapp.k14s.io/update-strategy: fallback-on-replace
    kapp.k14s.io/change-group: "kube-workflow/post-{{ .Values.global.namespace }}"
    kapp.k14s.io/change-rule: "upsert after upserting kube-workflow/{{ .Values.global.namespace }}"
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 3600
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      annotations: {}
      labels: {}
    spec:
      restartPolicy: Never
      containers:          
        - name: job
          image: "debian:stable"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - rm -rf /workflow/*
          volumeMounts:
            - name: workflow
              mountPath: /workflow
              subPath: {{ .Values.global.branchSlug }}/{{ .Values.global.sha }}

      volumes:
        - name: workflow
          persistentVolumeClaim:
            claimName: jobs-shared-storage
{{- end }}