## mandatory
ciNamespace: ""
host: ""


## default
createNamespace: false
replicas: 1
isProdCluster: true
containerPort: 3000
image: harbor.fabrique.social.gouv.fr/sre/kontinuous/webhook:latest
# image: ghcr.io/socialgouv/kontinuous/webhook:latest
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

## optional
rancherProjectId: ""
component: ""
certSecretName: ""
secretRefNames:
  - kubeconfig-dev
  - kubeconfig-prod
  - kubewebhook

artifacts:
  storage:
    size: 2Gi
    className: 'azurefile'