## mandatory
rancherProjectName: ""


## default
replicas: 1
isProdCluster: true
image: ghcr.io/socialgouv/kube-workflow/webhook:latest
# image: harbor.fabrique.social.gouv.fr/sre/kube-workflow/webhook:latest
baseDomain: "fabrique.social.gouv.fr"
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
    
## optional
rancherProjectId: ""
component: ""
certSecretName: ""
host: ""
secretRefNames:
  - kubeconfig
  - kubewebhook
