## mandatory
host: ""


## default
createNamespace: false
replicas: 2
isProdCluster: true
containerPort: 3000
image: harbor.fabrique.social.gouv.fr/sre/kontinuous/webhook:latest
# image: ghcr.io/socialgouv/kontinuous/webhook:v1.95.18
resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi
terminationGracePeriodSeconds: 900

## optional
rancherProjectId: ""
component: ""
certSecretName: ""

artifacts:
  storage:
    size: 2Gi
    className: 'azurefile'

httpLogger:
  ignoreUserAgents:
    - blackbox-monitoring-fabnum

pipelineCheckoutImage: ghcr.io/socialgouv/kontinuous/degit
pipelineCheckoutImageTag: v1
pipelineImage: ghcr.io/socialgouv/kontinuous
pipelineImageTag: v1
# pipelineCheckoutImage: harbor.fabrique.social.gouv.fr/sre/kontinuous/degit:v1
# pipelineImage: harbor.fabrique.social.gouv.fr/sre/kontinuous:v1

# ACL
rootTokenSecret:
rootTokenSecretKey: TOKEN
rootKubeconfigSecrets: []
kubeconfigSecrets: []
tokenSecrets: []
repositories: []