## mandatory
host: ""


## default
createNamespace: false
replicas: 2
isProdCluster: true
containerPort: 3000
image: harbor.fabrique.social.gouv.fr/sre/kontinuous/webhook:latest
# image: ghcr.io/socialgouv/kontinuous/webhook:latest
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi
terminationGracePeriod: 900

## optional
rancherProjectId: ""
component: ""
certSecretName: ""

artifacts:
  storage:
    size: 2Gi
    className: 'azurefile'

httpLogger:
  ignoreUserAgents:
    - blackbox-monitoring-fabnum

pipelineCheckoutImage: ghcr.io/socialgouv/kontinuous/degit:1
pipelineImage: ghcr.io/socialgouv/kontinuous:1
# pipelineCheckoutImage: harbor.fabrique.social.gouv.fr/sre/kontinuous/degit:v1
# pipelineImage: harbor.fabrique.social.gouv.fr/sre/kontinuous:v1

# ACL
kubeconfigSecrets: []
tokenSecrets: []