## mandatory
rancherProjectName: ""


## default
createNamespace: false
replicas: 1
isProdCluster: true
image: ghcr.io/socialgouv/kube-workflow/webhook:latest
containerPort: 3000
# image: harbor.fabrique.social.gouv.fr/sre/kube-workflow/webhook:latest
baseDomain: "fabrique.social.gouv.fr"
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

## optional
namespace: ""
rancherProjectId: ""
component: ""
certSecretName: ""
host: ""
secretRefNames:
  - kubeconfig-dev
  - kubeconfig-prod
  - kubewebhook
