## mandatory
ciNamespace: ""
host: ""


## default
createNamespace: false
replicas: 1
isProdCluster: true
containerPort: 3000
image: harbor.fabrique.social.gouv.fr/sre/kontinuous/webhook:latest
# image: ghcr.io/socialgouv/kontinuous/webhook:latest
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

## optional
rancherProjectId: ""
component: ""
certSecretName: ""

artifacts:
  storage:
    size: 2Gi
    className: 'azurefile'

# ACL
kubeconfigSecrets: []
tokenSecrets: []