apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{.Values.component }}
    application: {{ .Values.global.repositoryName }}
  name: {{.Values.component }}
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: 8081
  selector:
    component: {{.Values.component }}
  type: ClusterIP
  