name: Build Docker Images

on:
  push:
    # branches:
    #   - "**"
    tags:
      - 'v*.*.*'

concurrency:
  cancel-in-progress: true
  group: build-docker-images-${{ github.ref_name }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: ""
            dockerfile: packages/kontinuous/Dockerfile
          - destination: "/webhook"
            dockerfile: packages/webhook/Dockerfile
          - destination: "/degit"
            dockerfile: packages/degit/Dockerfile
          - destination: "/wait-needs"
            dockerfile: packages/wait-needs/Dockerfile
          - destination: "/gh-actions-common"
            dockerfile: packages/gh-actions/Dockerfile
            context: packages/gh-actions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}${{ matrix.destination }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context || "." }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      