name: Build Docker Images

on:
  push:
    branches:
      - '**'
      - '!master'
    tags:
      - 'v*.*.*'

concurrency:
  cancel-in-progress: true
  group: build-docker-images-${{ github.ref_name }}

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: ""
            dockerfile: packages/kontinuous/Dockerfile
          - destination: "/webhook"
            dockerfile: packages/webhook/Dockerfile
          - destination: "/degit"
            dockerfile: packages/degit/Dockerfile
          - destination: "/wait-needs"
            dockerfile: packages/wait-needs/Dockerfile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build image
        uses: ./.github/actions/build-images
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ matrix.context }}
          dockerfile: ${{ matrix.dockerfile }}
          destination: ${{ matrix.destination }}
  
  build-actions:
    needs: [build-base-images]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "/deploy-via-github"
            dockerfile: .github/actions/deploy-via-github/Dockerfile
            context: .github/actions/deploy-via-github
          - destination: "/deploy-via-webhook"
            dockerfile: .github/actions/deploy-via-webhook/Dockerfile
            context: .github/actions/deploy-via-webhook
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build image
        uses: ./.github/actions/build-images
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ matrix.context }}
          dockerfile: ${{ matrix.dockerfile }}
          destination: ${{ matrix.destination }}
    