name: Build Docker on ghcr

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get variables
        id: variables
        shell: bash
        run: |
          REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}          
          IMAGE_NAME="$REPOSITORY_NAME"
          echo "::set-output name=repository-name::$REPOSITORY_NAME"
          echo "::set-output name=image-name::$IMAGE_NAME"

      - name: Create image labels and tags
        id: docker_meta
        uses: "crazy-max/ghaction-docker-meta@2e1a5c7fa42123697f82d479b551a1bbdb1bef88"
        with:
          images: ghcr.io/socialgouv/${{ steps.variables.outputs.image-name }}
          labels: |
            org.opencontainers.image.title=${{ steps.variables.outputs.repository-name }}
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/tree/${{ github.sha }}
          tags: |
            type=sha
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=sha-${{ github.sha }}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Registry authentication
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image build and register
        uses: docker/build-push-action@v2
        with:
          push: "true"
          file: Dockerfile
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          tags: "${{ steps.docker_meta.outputs.tags }}"
          labels: "${{ steps.docker_meta.outputs.labels }}"
          cache-from: "type=gha,scope=${{ steps.variables.outputs.image-name }}-cache"
          cache-to: "type=gha,scope=${{ steps.variables.outputs.image-name }}-cache,mode=max"
