name: Build Docker Image Webhook

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.ref }}

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build image
        uses: ./.github/actions/build-images
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: packages/webhook/Dockerfile
          destination: /webhook
  