name: Release

on:
  push:
    tags:
      - v*.*

concurrency:
  cancel-in-progress: true
  group: release-${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: prepublish
        shell: bash
        run: |
          cd packages/kontinuous
          rm -f common && cp -r ../common ./
          rm -f LICENSE && cp -r ../../LICENSE ./
          rm -f README.md && cp -r ../../README.md ./
          node -e " \
            let package = JSON.parse(fs.readFileSync('package.json')); \
            const commonPackage = JSON.parse(fs.readFileSync('common/package.json')); \
            package.dependencies = { \
              ...commonPackage.dependencies, \
              ...package.dependencies, \
            }; \
            package._moduleAliases = { \
              ...package._moduleAliases, \
              '~common': 'common' \
            }; \
            delete package.dependencies['~common']; \
            fs.writeFileSync('package.json', JSON.stringify(package)); \
          "

      - id: publish-kontinuous
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.SOCIALGROOVYBOT_NPM_TOKEN }}
          package: packages/kontinuous/package.json
      
      - if: steps.publish-kontinuous.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish-kontinuous.outputs.old-version }} => ${{ steps.publish-kontinuous.outputs.version }}"
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
          generate_release_notes: true
