name: ✨ Release Publish

on:
  push:
    tags:
      - v*.*

permissions:
  id-token: write
  contents: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm
        run: npm install -g npm@latest

      - name: yarn install
        run: yarn --immutable

      - name: build with ncc
        run: yarn workspace kontinuous build

      - name: prepublish
        run: |
          cp LICENSE README.md packages/kontinuous/
          cat <<< $(jq "del(.dependencies, .devDependencies, .scripts, .main, ._moduleAliases)" packages/kontinuous/package.json) > packages/kontinuous/package.json

      - name: extract npm tag
        id: npm-tag
        run: |
          if [[ "$GITHUB_REF" == *"alpha"* ]]; then
            npm_tag="alpha"
          elif [[ "$GITHUB_REF" == *"beta"* ]]; then
            npm_tag="beta"
          else
            npm_tag="latest"
          fi
          echo "tag=$npm_tag" >> $GITHUB_OUTPUT

      - name: Publish to npm
        working-directory: packages/kontinuous
        run: npm publish --tag ${{ steps.npm-tag.outputs.tag }} --provenance --access public

      - name: Get GitHub App Token
        id: token
        uses: SocialGouv/token-bureau@main
        with:
          token-bureau-url: https://token-bureau.fabrique.social.gouv.fr
          audience: socialgouv

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ steps.token.outputs.token }}
          generate_release_notes: true
