name: ✨ Release Publish

on:
  push:
    tags:
      - v*.*

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: prepublish
        shell: bash
        run: |
          cp LICENSE README.md packages/kontinuous/
          yarn workspace kontinuous build

      - id: publish-kontinuous
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.SOCIALGROOVYBOT_NPM_TOKEN }}
          package: packages/kontinuous/package.json
      
      - if: steps.publish-kontinuous.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish-kontinuous.outputs.old-version }} => ${{ steps.publish-kontinuous.outputs.version }}"
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
          generate_release_notes: true
