name: Sync gh-pages

on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - README.md

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}

      - name: Run GitHub File Sync
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
        run: |
          set -x
          git remote set-url --push origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git fetch origin gh-pages:gh-pages
          git fetch origin master
          git checkout gh-pages
          git checkout master -- README.md
          rm index.md
          mv README.md index.md
          git add index.md
          git commit -a -m "Sync README.md in master branch to index.md in gh-pages"
          git push origin gh-pages