name: Tests Charts and Publish npx package

on:
  push:
    branches:
      - "*"

concurrency:
  cancel-in-progress: true
  group: tests-${{ github.head_ref }}

jobs:

  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Run tests
        run: yarn test
    
  publish:
    name: NPM Publish if version has been updated
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.SOCIALGROOVYBOT_NPM_TOKEN }}
      
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"