name: ✅ Tests build 📃

on:
  push:
    branches:
      - "**"
      - "!v*"
    tags-ignore:
      - "**"

concurrency:
  cancel-in-progress: true
  group: tests-build-${{ github.ref_name }}

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      
      - name: Yarn install
        run: |
          yarn workspaces focus kontinuous --production

      - name: write .kontinuous/config.yaml
        shell: bash
        run: |
          mkdir -p $HOME/.kontinuous
          echo "
          links:
            socialgouv/kontinuous: ${GITHUB_WORKSPACE}
          " > $HOME/.kontinuous/config.yaml

      - name: Install dependencies
        run: yarn --immutable

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Run plugins contrib
        run: |
          yarn --cwd plugins/contrib
          yarn --cwd plugins/contrib test
