name: Trigger Release

on: 
  workflow_dispatch:
    
concurrency:
  cancel-in-progress: true
  group: release-${{ github.ref_name }}

jobs:
  yarn-release:
    runs-on: ubuntu-latest
    name: Create release using standard-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Run release
        env:
          GIT_AUTHOR_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
        run: yarn release
      
      - name: Push release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url --push origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push -f --tags origin master