on:
  workflow_call:
    inputs:
      disableDiff:
        type: string
        required: false
      environment:
        type: string
        required: false
      chart:
        type: string
        required: false
      ignoreProjectTemplates:
        type: boolean
        required: false

jobs:
  deploy:
    name: Kontinuous Deployment Pipeline 🚀
    runs-on: ubuntu-latest
    steps:
      - name: kontinuous pipeline
        uses: socialgouv/kontinuous/.github/actions/deploy-via-github@v1.111.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          ciNamespace: "${{ secrets.RANCHER_PROJECT_NAME }}-ci"
          environment: "${{ inputs.environment }}"
          disableDiff: "${{ inputs.disableDiff }}"
          chart: "${{ inputs.chart }}"
          ignoreProjectTemplates: "${{ inputs.ignoreProjectTemplates }}"
